#!/usr/bin/python
import os, sys
from subprocess import call, Popen, PIPE

if len(sys.argv) == 1:
	print "ERROR : project name is not indicated"
	print "usage : wafnew <project-name>"
	exit(1)

newdir = sys.argv[1]

if os.path.exists(newdir):
	print "the dir already exists"
	exit(1)

print "building waf template project : " + newdir

call(["mkdir", "-p", "/tmp/waf-tmp"])
call(["rm", "-rf", "*"])
p1 = Popen(["curl", "-s", "-f", "-L", "https://github.com/nakajijiji/waf-template/tarball/master"], stdout=PIPE)
p2 = Popen(["tar", "xvz", "-C", "/tmp/waf-tmp"], stdin=p1.stdout, stdout=PIPE)
p1.stdout.close()
output = p2.communicate()[0]

dir = output.split("\n")[0][:-1]

call(["mv", "/tmp/waf-tmp/" + dir, newdir])
call(["rm", "-rf", "*"])
print "SUCCESS!!"
